# Generated by Django 5.0.3 on 2024-03-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoListProject', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskCompleted',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='whenCreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskTitle',
            new_name='title',
        ),
    ]
