# Generated by Django 5.0.3 on 2024-03-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoListProject', '0004_task_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='password',
        ),
    ]
